"""Trading signal model for execution and analysis workflows."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime


@dataclass(slots=True, frozen=True)
class Signal:
    """Represents a trading signal generated by the platform."""

    symbol: str
    direction: str
    entry: float
    stop_loss: float
    take_profit: float
    confidence: float
    nova_score: float
    timeframe: str
    created_at: datetime

    def __post_init__(self) -> None:
        """Validate the signal attributes and score ranges."""
        if not self.symbol.strip():
            raise ValueError("symbol cannot be empty")
        if not self.direction.strip():
            raise ValueError("direction cannot be empty")
        if not self.timeframe.strip():
            raise ValueError("timeframe cannot be empty")
        if self.entry <= 0 or self.stop_loss <= 0 or self.take_profit <= 0:
            raise ValueError("entry, stop_loss, and take_profit must be positive")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")
        if not 0.0 <= self.nova_score <= 1.0:
            raise ValueError("nova_score must be between 0.0 and 1.0")
        if self.created_at.tzinfo is None:
            raise ValueError("created_at must be timezone-aware")
        object.__setattr__(self, "symbol", self.symbol.strip().upper())
        object.__setattr__(self, "direction", self.direction.strip().lower())
        object.__setattr__(self, "timeframe", self.timeframe.strip().upper())

    def risk_reward(self) -> float:
        """Return the risk-reward ratio based on the configured levels."""
        if self.entry == self.stop_loss:
            return float("inf")
        return abs(self.take_profit - self.entry) / abs(self.entry - self.stop_loss)

    def __repr__(self) -> str:
        """Provide a concise, readable representation of the signal."""
        return (
            f"Signal(symbol={self.symbol!r}, direction={self.direction!r}, "
            f"entry={self.entry}, stop_loss={self.stop_loss}, take_profit={self.take_profit}, "
            f"confidence={self.confidence}, nova_score={self.nova_score}, "
            f"timeframe={self.timeframe!r}, created_at={self.created_at!r})"
        )
